name: Build
on:
  push:
    branches:
    - main
    paths-ignore:
    - "README.md"
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Minimum JDK is 17
        java_version: ['17', '21']
        os: ['ubuntu-20.04']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      run: ./mvnw -B -q -ff -ntp verify
    - name: Generate code coverage
      if: github.event_name != 'pull_request' && matrix.java_version == '8'
      run: ./mvnw -B -q -ff -ntp test
    - name: Publish code coverage
      if: github.event_name != 'pull_request' && matrix.java_version == '8'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
